export enum Actions {
  inputhub = 1,
  actionsheet,

  addProject = 64,
  newProjectAction,
  zipChoose,
  tuijian,

  gitClone = 128,
  gitCloneAction,
}

export const supportLanguageMap = {
  json: "json",
  md: "markdown",
  js: "javascript",
  jsx: "javascript",
  tsx: "typescript",
  ts: "typescript",
  xml: "xml",
  c: "c",
  h: "c",
  cc: "cpp",
  cpp: "cpp",
  hpp: "cpp",
  cs: "csharp",
  cmake: "cmake",
  dart: "dart",
  docker: "dockerfile",
  erl: "erlang",
  xls: "excel",
  go: "go",
  groovy: "groovy",
  ini: "ini",
  java: "java",
  julia: "jl",
  kt: "kotlin",
  less: "less",
  llvm: "llvm",
  lua: "lua",
  m: "matlab",
  php: "php",
  text: "plaintext",
  py: "python",
  sh: "shell",
  sql: "sql",
  styl: "stylus",
  swift: "swift",
  yaml: "yaml",
  wat: "wasm",
  vim: "vim"
}
